/**
 * Backfill invoice PDFs for paid orders that don't have an invoiceUrl yet.
 *
 * Iterates the orders table, filters for paymentStatus=CAPTURED and
 * !invoiceUrl, and for each one:
 *   1. Builds the invoice PDF (services/invoicePdf)
 *   2. Uploads it to the invoices blob container (services/blobStorage)
 *   3. Stamps invoiceUrl on the order row
 *   4. Appends an order event so the backfill is auditable
 *
 * NO notifications are sent. Backfill is a data hygiene operation, not
 * a customer-facing one - we don't want to re-email or re-WhatsApp
 * historic customers months after the fact.
 *
 * Defaults to DRY RUN. Pass --apply to commit.
 *
 * Usage (PowerShell):
 *   $env:AZURE_STORAGE_ACCOUNT_NAME="stthesrilathaartsdev"
 *   $env:BLOB_BASE_URL="https://stthesrilathaartsdev.blob.core.windows.net"
 *   npx ts-node scripts/backfillInvoices.ts          # dry run
 *   npx ts-node scripts/backfillInvoices.ts --apply  # commit
 *
 * Requires: az login (DefaultAzureCredential), and the invoices blob
 * container must exist (provisioned by infra/Deploy-Infrastructure.ps1).
 */

import {
  getAllOrders,
  getOrderItems,
  mergeOrder,
  appendOrderEvent,
} from '../src/services/tableStorage'
import { buildInvoicePdf } from '../src/services/invoicePdf'
import { uploadInvoicePdf } from '../src/services/blobStorage'
import { invoiceUrlFor } from '../src/services/orderNumber'

const APPLY = process.argv.includes('--apply')

interface BackfillSummary {
  scanned: number
  eligible: number
  uploaded: number
  failed: number
}

async function backfill(): Promise<BackfillSummary> {
  const orders = await getAllOrders()
  const summary: BackfillSummary = { scanned: orders.length, eligible: 0, uploaded: 0, failed: 0 }
  console.log(`[backfill] account=${process.env.AZURE_STORAGE_ACCOUNT_NAME} dryRun=${!APPLY}`)
  console.log(`[backfill] scanned ${orders.length} orders`)

  const targets = orders.filter(
    (o) => o.paymentStatus === 'CAPTURED' && !o.invoiceUrl,
  )
  summary.eligible = targets.length
  console.log(`[backfill] ${targets.length} paid orders missing invoiceUrl`)

  if (!APPLY) {
    targets.slice(0, 10).forEach((o) => {
      console.log(`         would generate for ${o.rowKey} (createdAt=${o.createdAt})`)
    })
    if (targets.length > 10) console.log(`         ... and ${targets.length - 10} more`)
    console.log('[backfill] dry run complete - pass --apply to commit')
    return summary
  }

  for (const order of targets) {
    const orderId = order.rowKey as string
    try {
      const items = await getOrderItems(orderId)
      const buf = await buildInvoicePdf(
        {
          id: orderId,
          status: order.status as string,
          paymentStatus: order.paymentStatus as string,
          displayTotal: Number(order.displayTotal ?? 0),
          subtotal: typeof order.subtotal === 'number' ? order.subtotal : undefined,
          shippingAmount: typeof order.shippingAmount === 'number' ? order.shippingAmount : undefined,
          discountAmount: typeof order.discountAmount === 'number' ? order.discountAmount : undefined,
          couponCode: (order.couponCode as string) || undefined,
          customerName: (order.customerName as string) || '',
          customerEmail: (order.customerEmail as string) || undefined,
          customerPhone: (order.customerPhone as string) || undefined,
          shippingAddress: parseAddress(order.shippingAddress),
          razorpayPaymentId: (order.razorpayPaymentId as string) || undefined,
          createdAt: (order.createdAt as string) || new Date().toISOString(),
        },
        items.map((i) => ({
          productId: i.rowKey as string,
          title: (i.title as string) || '',
          category: (i.category as string) || '',
          imageUrl: (i.imageUrl as string) || undefined,
          displayPrice: Number(i.displayPrice ?? 0),
          qty: Number(i.qty ?? 1),
        })),
      )
      await uploadInvoicePdf(orderId, buf)
      const brandedUrl = invoiceUrlFor(orderId)
      const now = new Date().toISOString()
      await mergeOrder(order.partitionKey as string, orderId, {
        invoiceUrl: brandedUrl,
        updatedAt: now,
      })
      await appendOrderEvent({
        partitionKey: orderId,
        rowKey: `${now}_invoice_backfill`,
        channel: 'system',
        by: 'backfill-script',
        byRole: 'system',
        note: 'Invoice generated by backfill script',
        meta: JSON.stringify({ invoiceUrl: brandedUrl }),
        createdAt: now,
      })
      summary.uploaded += 1
      console.log(`[backfill] ${orderId} -> uploaded`)
    } catch (err) {
      summary.failed += 1
      console.error(`[backfill] ${orderId} FAILED:`, (err as Error).message)
    }
  }

  return summary
}

function parseAddress(raw: unknown):
  | { fullName?: string; phone?: string; line1?: string; line2?: string; city?: string; state?: string; pincode?: string; country?: string }
  | undefined {
  if (!raw) return undefined
  if (typeof raw === 'object') return raw as Record<string, string>
  try { return JSON.parse(String(raw)) } catch { return undefined }
}

backfill()
  .then((s) => {
    console.log('[backfill] done:', s)
  })
  .catch((err) => {
    console.error('[backfill] fatal:', err)
    process.exit(1)
  })
