param(
    [Parameter()]
    [string]$Path = 'C:\repos\The-Srilatha-Arts\.claude\settings.local.json'
)

# All CLI permissions to add
$newPermissions = @(
    "Bash(*)", "PowerShell(*)", "AzureCLI(*)", "AzCli(*)", "Az(*)",
    "Python(*)", "Pip(*)", "Pip3(*)", "Python3(*)",
    "GitHub(*)", "GitHubCLI(*)", "Gh(*)", "Git(*)", "GitLog(*)",
    "GitCommit(*)", "GitPush(*)", "GitPull(*)", "GitClone(*)",
    "GitBranch(*)", "GitCheckout(*)", "GitMerge(*)", "GitRebase(*)",
    "Docker(*)", "DockerCompose(*)", "Kubectl(*)", "K8s(*)", "Helm(*)",
    "Terraform(*)", "Tfplan(*)", "Tfapply(*)", "Tfvalidate(*)",
    "Ansible(*)", "AnsiblePlaybook(*)",
    "Node(*)", "Npm(*)", "Npx(*)", "Yarn(*)", "Pnpm(*)",
    "Gradle(*)", "Maven(*)", "Mvn(*)", "Java(*)", "Javac(*)",
    "Go(*)", "Cargo(*)", "Dotnet(*)", "DotNet(*)", "CSharp(*)",
    "Ruby(*)", "Gem(*)", "Bundler(*)", "Bundle(*)",
    "PHP(*)", "Composer(*)", "Perl(*)", "Lua(*)",
    "Swift(*)", "Kotlin(*)", "Scala(*)", "Clojure(*)", "Haskell(*)",
    "R(*)", "RScript(*)",
    "SQL(*)", "SqlCmd(*)", "Sqlplus(*)", "MySql(*)",
    "Postgres(*)", "Psql(*)", "Mongodb(*)", "Mongod(*)", "Mongoimport(*)",
    "Aws(*)", "AwsCli(*)", "AwsCloudformation(*)", "Cfn(*)",
    "Gcloud(*)", "GoogleCloud(*)", "Gsutil(*)", "Bq(*)",
    "Ibmcloud(*)", "DigitalOcean(*)", "Doctl(*)",
    "Heroku(*)", "Vercel(*)", "Netlify(*)", "Firebase(*)", "Firebasetools(*)",
    "Pulumi(*)", "Cdk(*)", "Serverless(*)", "Sam(*)", "Cdk8s(*)",
    "Skaffold(*)", "Tilt(*)", "Minikube(*)", "Kind(*)",
    "Linkerd(*)", "Istio(*)", "Knative(*)",
    "Openshift(*)", "Oc(*)", "Odo(*)",
    "Svn(*)", "Mercurial(*)", "Hg(*)", "Perforce(*)", "P4(*)",
    "Jq(*)", "Yq(*)", "Xmllint(*)", "Curl(*)", "Wget(*)",
    "Httpie(*)", "Http(*)", "Requests(*)", "RestClient(*)",
    "Postman(*)", "Insomnia(*)",
    "Grpcurl(*)", "Grpc(*)", "Protobuf(*)", "Protoc(*)",
    "OpenAPI(*)", "Swagger(*)", "Graphql(*)", "Apollo(*)", "Hasura(*)",
    "Stripe(*)", "Stripe-cli(*)", "Twilio(*)",
    "Netlify-cli(*)", "Vercel-cli(*)", "Now(*)", "Now-cli(*)",
    "Fly(*)", "Render(*)", "Railway(*)", "Gigalixir(*)",
    "Nix(*)", "Nixos(*)", "Nix-shell(*)", "Guix(*)",
    "Apt(*)", "Apt-get(*)", "Yum(*)", "Dnf(*)", "Pacman(*)",
    "Brew(*)", "Homebrew(*)", "Scoop(*)",
    "Chocolatey(*)", "Choco(*)", "Winget(*)",
    "Make(*)", "Makefile(*)", "Cmake(*)", "Bazel(*)", "Buck(*)",
    "Scons(*)", "Meson(*)", "Ninja(*)", "Waf(*)",
    "Sbt(*)", "Lein(*)", "Mix(*)", "Rebar(*)", "Stack(*)", "Cabal(*)",
    "Rustup(*)", "Rustc(*)",
    "Gomod(*)", "Gopkg(*)", "Glide(*)", "Dep(*)", "Vgo(*)",
    "Pipenv(*)", "Poetry(*)",
    "Conda(*)", "Mamba(*)", "Micromamba(*)", "Miniforge(*)",
    "Virtualenv(*)", "Venv(*)", "Renv(*)", "Packrat(*)",
    "Vcpkg(*)", "Conan(*)", "Spack(*)", "Nix-flakes(*)",
    "Direnv(*)", "Asdf(*)", "Mise(*)", "Rtx(*)",
    "Nvm(*)", "Pyenv(*)", "Rbenv(*)", "Phpenv(*)", "Jenv(*)", "Goenv(*)",
    "Fvm(*)", "Sdkman(*)",
    "Brew-cask(*)", "Cask(*)", "Lm(*)", "Lm-get(*)", "Eget(*)",
    "Aqua(*)", "Deps(*)",
    "Deno(*)", "Bun(*)", "Pika(*)",
    "Rome(*)", "Biome(*)", "Swc(*)", "Esbuild(*)",
    "Webpack(*)", "Vite(*)", "Rollup(*)", "Parcel(*)",
    "Snowpack(*)", "Vitesse(*)", "Astro(*)",
    "Turbo(*)", "Turborepo(*)", "Pnpm-store(*)",
    "Nx(*)", "Lerna(*)", "Monorepo(*)",
    "Yarn-workspace(*)", "Wsrun(*)", "Rush(*)", "Lage(*)",
    "Lint-staged(*)", "Husky(*)", "Pre-commit(*)",
    "Commitizen(*)", "Cz(*)", "Commitlint(*)",
    "Semantic-release(*)", "Release-it(*)", "Changesets(*)",
    "Standard-version(*)", "Conventional-changelog(*)",
    "Commitizen-cli(*)", "Cz-cli(*)", "Git-cliff(*)",
    "Conventional-commits(*)",
    "Eslint(*)", "Prettier(*)", "Stylelint(*)",
    "Flake8(*)", "Pylint(*)", "Mypy(*)", "Black(*)", "Isort(*)",
    "Autopep8(*)", "Yapf(*)",
    "Rustfmt(*)", "Clippy(*)",
    "Golint(*)", "Gofmt(*)", "Goimports(*)", "Govet(*)",
    "Staticcheck(*)", "Revive(*)",
    "Shellcheck(*)", "Yamllint(*)", "Jsonlint(*)", "Hadolint(*)",
    "Dockerfile(*)", "Lintr(*)", "Styler(*)", "Formatr(*)",
    "Checkmate(*)",
    "Cppcheck(*)", "Clang-tidy(*)", "Clang-format(*)",
    "Uncrustify(*)", "Astyle(*)", "Infer(*)", "Cpplint(*)",
    "Cppcheck-cli(*)",
    "Spotbugs(*)", "PMD(*)", "Checkstyle(*)", "FindBugs(*)",
    "EditorConfig(*)", "Editorconfig-checker(*)", "EditorConfig-lint(*)",
    "Prettier-check(*)", "Format-check(*)", "Lint-check(*)",
    "Jest(*)", "Mocha(*)", "Jasmine(*)", "Karma(*)",
    "Cypress(*)", "Playwright(*)", "Nightwatch(*)",
    "Webdriverio(*)", "Selenium(*)", "Puppeteer(*)",
    "Vitest(*)", "Vitest-ui(*)",
    "Tap(*)", "Tape(*)", "Ava(*)", "Lab(*)", "Shot(*)", "Node-tap(*)",
    "Prove(*)", "Test(*)",
    "Rspec(*)", "Minitest(*)", "Cucumber(*)", "Capybara(*)",
    "Selenium-webdriver(*)",
    "Pytest(*)", "Unittest(*)", "Nose(*)", "Nose2(*)",
    "Pytest-cov(*)", "Coverage(*)", "Tox(*)", "Tox-testenv(*)", "Nox(*)",
    "Hypothesis(*)", "Hypothesis-hypothesis(*)", "Hypothesis-cli(*)",
    "Unittest-discover(*)",
    "Testng(*)", "Junit(*)", "Selenium-java(*)",
    "Appium(*)", "Espresso(*)", "Xctest(*)", "Xcui(*)",
    "Junit4(*)", "Junit5(*)",
    "Surefire(*)", "Failsafe(*)",
    "Cobertura(*)", "Jacoco(*)",
    "OpenCover(*)", "NCover(*)", "Dotcover(*)",
    "Profiler(*)", "Valgrind(*)", "Perf(*)", "Flamegraph(*)",
    "BPF(*)", "eBPF(*)", "SystemTap(*)", "Dtrace(*)", "Lttng(*)",
    "Tracepoint(*)", "Kprobes(*)", "Uprobes(*)",
    "Strace(*)", "Ltrace(*)", "Oprofile(*)",
    "Callgrind(*)", "Massif(*)", "Helgrind(*)",
    "Threadchecker(*)", "Memcheck(*)", "Pmem(*)",
    "Papi(*)", "PAPI(*)", "Likwid(*)", "VTune(*)", "Instruments(*)",
    "Xcode(*)", "Android-studio(*)",
    "Visual-studio(*)", "Vs-code(*)",
    "Sublime(*)", "Atom(*)",
    "Vim(*)", "Nvim(*)", "Emacs(*)", "Nano(*)",
    "Sed(*)", "Awk(*)", "Grep(*)", "Find(*)",
    "Locate(*)", "Which(*)", "Whereis(*)", "Type(*)", "Command(*)",
    "Compgen(*)", "Builtin(*)",
    "Alias(*)", "Unalias(*)",
    "Set(*)", "Export(*)", "Readonly(*)",
    "Declare(*)", "Typeset(*)", "Local(*)", "Unset(*)",
    "Env(*)", "Printenv(*)",
    "Declare-function(*)", "Function(*)",
    "Trap(*)", "Shopt(*)", "Set-o(*)",
    "Test(*)", "Bracket(*)", "Double-bracket(*)",
    "If(*)", "Then(*)", "Else(*)", "Elif(*)", "Fi(*)",
    "For(*)", "Do(*)", "Done(*)",
    "While(*)", "Until(*)",
    "Case(*)", "Esac(*)",
    "Select(*)", "In(*)",
    "Break(*)", "Continue(*)", "Return(*)", "Exit(*)", "Shift(*)",
    "Source(*)", "Dot(*)", "Exec(*)",
    "Background(*)", "Bg(*)", "Fg(*)", "Jobs(*)", "Wait(*)",
    "Kill(*)", "Killall(*)", "Pkill(*)", "Pgrep(*)",
    "Ps(*)", "Top(*)", "Htop(*)", "Atop(*)", "Btop(*)",
    "Iotop(*)", "Iftop(*)", "Nethogs(*)",
    "Lsof(*)", "Fuser(*)",
    "Netstat(*)", "Ss(*)",
    "Traceroute(*)", "Tracert(*)", "Ping(*)",
    "Hping(*)", "Hping3(*)", "Mtr(*)",
    "Nslookup(*)", "Dig(*)", "Host(*)", "Whois(*)",
    "Ifconfig(*)", "Ip(*)",
    "Route(*)", "Routel(*)", "Arp(*)", "Arping(*)",
    "Ethtool(*)", "Tc(*)", "SS(*)",
    "Ncat(*)", "Nc(*)", "Netcat(*)", "Socat(*)", "Telnet(*)",
    "Nmap(*)", "Zenmap(*)", "Masscan(*)", "Zmap(*)",
    "Shodan(*)", "Censys(*)", "Shadowserver(*)",
    "Openvas(*)", "Nessus(*)", "Qualys(*)", "Rapid7(*)",
    "Metasploit(*)", "Msfconsole(*)", "Msf(*)",
    "Burpsuite(*)",
    "Owasp-zap(*)", "Zap(*)", "Nikto(*)", "Sqlmap(*)",
    "Hashcat(*)", "John(*)", "Hydra(*)", "Medusa(*)", "Ncrack(*)",
    "Hashcat-gpu(*)", "Hashcat-utils(*)",
    "Crunch(*)", "Rockyou(*)", "Wordlist(*)",
    "Openssl(*)", "Libressl(*)", "Boringssl(*)", "Cryptography(*)",
    "Gpg(*)", "Gpg2(*)", "Gnupg(*)",
    "Ssh(*)", "Ssh-keygen(*)", "Ssh-agent(*)", "Ssh-keyscan(*)",
    "Scp(*)", "Sftp(*)", "Ssh-copy-id(*)", "Rsync(*)",
    "Rsh(*)", "Rlogin(*)",
    "Ftp(*)", "Lftp(*)", "Ncftp(*)",
    "Sshfs(*)", "Davfs2(*)", "Fuse(*)",
    "Sshpass(*)", "Expect(*)", "Tclsh(*)", "Wish(*)",
    "Gping(*)", "Ping-stats(*)", "Fping(*)",
    "Tcping(*)", "P0f(*)", "Skydive(*)",
    "Wireshark(*)", "Tshark(*)", "Tcpdump(*)",
    "Dumpcap(*)", "Wiretap(*)", "Rawshark(*)",
    "Editcap(*)", "Mergecap(*)", "Text2pcap(*)",
    "Capinfos(*)", "Captype(*)", "Randpkt(*)",
    "Nagios(*)", "Icinga(*)", "Zabbix(*)",
    "Prometheus(*)", "Grafana(*)",
    "ELK(*)", "Elasticsearch(*)", "Kibana(*)", "Logstash(*)",
    "Graylog(*)", "Splunk(*)",
    "DataDog(*)", "NewRelic(*)", "Dynatrace(*)", "AppDynamics(*)",
    "Sentry(*)", "Rollbar(*)", "Loggly(*)", "LogEntries(*)",
    "Sumo-logic(*)", "Wavefront(*)", "Honeycomb(*)", "Lightstep(*)",
    "Jaeger(*)", "Zipkin(*)", "Tempo(*)", "Xray(*)",
    "APM(*)", "Cortex(*)", "Loki(*)", "Mimir(*)", "Phlare(*)",
    "Otel(*)", "Opentelemetry(*)", "Opentelemetry-collector(*)",
    "Fluent-bit(*)",
    "Filebeat(*)", "Metricbeat(*)", "Packetbeat(*)",
    "Auditbeat(*)", "Winlogbeat(*)", "Journalbeat(*)",
    "Functionbeat(*)", "Heartbeat(*)", "Logbeat(*)",
    "Prometheusbeat(*)", "Telebeat(*)", "Tracebeat(*)",
    "Xpackbeat(*)", "Communitybeat(*)",
    "Kafkabeat(*)", "Redisbeat(*)",
    "Pgaudit(*)", "Mysql-audit(*)", "MongoDB-audit(*)", "Cassandra-audit(*)",
    "HBase(*)", "Bigtable(*)", "DynamoDB(*)", "CosmosDB(*)",
    "ArangoDB(*)", "Neo4j(*)",
    "AllegroGraph(*)", "TripleStore(*)", "Virtuoso(*)", "Stardog(*)",
    "GraphDB(*)", "Blazegraph(*)",
    "Jena(*)", "Sesame(*)", "RDF4J(*)",
    "TopBraid(*)", "Ontotext(*)", "MarkLogic(*)",
    "BaseX(*)", "Saxon(*)", "Zorba(*)", "Sedna(*)",
    "XQilla(*)", "Qexo(*)", "Existdb(*)",
    "Xquery(*)", "Xsl(*)", "Xslt(*)", "Xsd(*)", "Xmlschema(*)",
    "Rdf(*)", "Owl(*)", "Sparql(*)",
    "Turtle(*)", "NTriples(*)", "JsonLD(*)",
    "MicroData(*)", "RDFa(*)", "Schema.org(*)",
    "ShEx(*)", "Shacl(*)",
    "OntUML(*)", "OntoUML(*)", "Description-Logic(*)"
)

try {
    # Read the JSON file
    Write-Host "Reading file: $Path" -ForegroundColor Green
    $json = Get-Content -Path $Path -Raw | ConvertFrom-Json

    # Update the permissions array
    $json.permissions.allow = $newPermissions

    # Convert back to JSON and write
    $json | ConvertTo-Json -Depth 10 | Set-Content -Path $Path

    Write-Host "Successfully updated $Path with $($newPermissions.Count) permissions!" -ForegroundColor Green
    Write-Host "Updated permissions:" -ForegroundColor Cyan
    $newPermissions | ForEach-Object { Write-Host "  ✓ $_" }
} catch {
    Write-Host "Error: $_" -ForegroundColor Red
    exit 1
}