'use client'
import Image, { type ImageProps } from 'next/image'

// Drop-in replacement for next/image that opportunistically serves the
// .webp companion produced by scripts/optimize-images.mjs and, for
// admin-uploaded product photos on blob storage, the responsive srcset
// variants generated by services/blobStorage.ts (audit M1).
//
// Why a wrapper and not next/image alone:
//   next.config.mjs sets `images.unoptimized: true` because the site
//   builds as a static export - there is no runtime image optimiser.
//   Without that, next/image just renders an <img> at the source URL,
//   so modern formats and responsive sizes only kick in if the markup
//   itself offers them.

function jpegToWebp(src: string): string | null {
  if (typeof src !== 'string') return null
  if (!src.startsWith('/') || src.startsWith('//')) return null
  if (!/\.(jpe?g)(?:$|\?)/i.test(src)) return null
  return src.replace(/\.(jpe?g)/i, '.webp')
}

// For blob-hosted product photos we uploaded via uploadProductImage,
// derive the three responsive variants (400/800/1200) that live alongside
// the primary URL - e.g. `.../resin/foo.webp` gets siblings
// `.../resin/foo-w400.webp` and `.../resin/foo-w800.webp`.
//
// Invariant: the -w400 / -w800 siblings MUST exist for every primary
// URL served through this component. The browser does NOT fall back to
// other srcset entries if a picked candidate 404s - it renders alt text.
// uploadProductImage writes all three variants atomically (Promise.all);
// legacy blobs uploaded before that pipeline are backfilled by
// backend/scripts/backfillImageVariants.ts. If you add a new upload path
// that lands anything in `products/`, it must produce the siblings too.
function productSrcSet(src: string): string | null {
  if (typeof src !== 'string') return null
  if (!/\.blob\.core\.windows\.net\/products\//.test(src)) return null
  if (!/\.webp(?:$|\?)/i.test(src)) return null
  const dotIdx = src.lastIndexOf('.')
  const base = src.slice(0, dotIdx)
  const ext = src.slice(dotIdx)
  const w400 = `${base}-w400${ext}`
  const w800 = `${base}-w800${ext}`
  return `${w400} 400w, ${w800} 800w, ${src} 1200w`
}

export default function PictureImage(props: ImageProps) {
  const { src } = props
  const webp = typeof src === 'string' ? jpegToWebp(src) : null
  const srcSet = typeof src === 'string' ? productSrcSet(src) : null
  if (!webp && !srcSet) return <Image {...props} />
  return (
    <picture style={{ display: 'contents' }}>
      {webp && <source srcSet={webp} type="image/webp" />}
      {srcSet && <source srcSet={srcSet} sizes={String(props.sizes ?? '100vw')} type="image/webp" />}
      <Image {...props} />
    </picture>
  )
}
